const num1 =10;
const num2 =21;
 const add = num1 + num2;
 const sub = num2 - num1;
 const mult = num1 * num2;
 const div = num2/num1;
 const  rem = num2%num1;
 console.log(add);
 console.log(sub);
 console.log(mult);
 console.log(div);
 console.log(rem);
 console.log(num1++);